[package]
name = "AES-256_encrypter_for_Midbar_Teensy_4_1_V3_1"
version = "0.3.1"
edition = "2021"

[dependencies]
druid = "0.8.3"
rand = "0.8.4"
hmac = "0.10.1"
sha2 = "0.9.6"
aes = "0.8.4"
hex = "0.4"
hex-literal = "0.3.4"
lazy_static = "1.4"
generic-array = "0.14.4"